#cloud-config

users:
  - name: marat
    groups: sudo
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    ssh_authorized_keys:
      - ssh-ed25519 AAAA***

disable_root: true
timezone: Europe/Moscow
repo_update: true
repo_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - unattended-upgrades
  - jq  

runcmd:
  - sudo apt update

